build: false
image: Previous Visual Studio 2015

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;C:\\blender-2.78a-windows64;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - "conda create -q -n test-environment numpy scipy"
  - activate test-environment
  - conda install -c scitools shapely
  - conda install -c ioos rtree
  - conda install -c conda-forge lxml scikit-image
  - pip install nose2 networkx svg.path sympy msgpack-python
  - pip install .
  - appveyor DownloadFile http://mirror.cs.umn.edu/blender.org/release/Blender2.78/blender-2.78c-windows64.zip
  - 7z x blender-2.78c-windows64.zip "-oC:\" -y


test_script:
  - nose2