language: python
sudo: required
dist: trusty

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'

before_deploy:
- pip install -r docs/requirements.txt
- python docs/build.py

# extract the current trimesh version from the version file
- export TMVERSION=`python -c "exec(open('trimesh/version.py','r').read()); print(__version__)"`

# tag the release and if it's already tagged chill
- git tag $TMVERSION || true

deploy:
- provider: pypi
  user: mikedh
  on:
    python: '3.6'
    branch: master
  password:
    secure: MmFES9M+UZbfpQsWeSVlhgUcdbpCymaeJwExxcyJbkKKWdRoZLRusqCmTdQ7Rai8DxH++ooqgEnHwq+D9e/8Y0jbbFBScPbJVeNFj1B4xV36NlyV8A0027/UTuhvkhoUv/xP6mN4TfuC3tWEj5m20DQlibjjxS154r/BlA6/kic=

- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: false
  target-branch: gh-pages
  local-dir: docs/html
  on:
    python: '3.6'
    branch: master

- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: false
  # only release the README github will create source
  # tarballs which are what people would want anyway
  file: "README.md"
  on:
    python: '3.6'
    branch: master

before_install:
- sudo apt-get update
- sudo apt-get install -y openscad blender meshlab xvfb pandoc
- sudo wget https://github.com/mikedh/v-hacd-1/raw/master/bin/linux/testVHACD --quiet
  -P /usr/bin
- sudo chmod +x /usr/bin/testVHACD

install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget --quiet https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nomkl numpy scipy
- source activate test-environment

# only install the basic version of the library to make sure
# trimesh imports and functions with only the minimal install
- pip install .

# install testing stuff
- pip install pytest pytest-cov coveralls

script:

# try simple tests with only minimal deps
- python -c "import trimesh"
- pytest tests/test_inertia.py

# shapely/rtree are easiest to get from conda
- conda install scikit-image rtree shapely

# pyembree and python-fcl not available everywhere
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then conda install pyembree; fi;
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then pip install python-fcl; fi;

# install most deps here
- pip install .[easy]

# xxhash only has linux wheels and triangle is compiled
- pip install triangle xxhash

# run main tests
- pytest --cov=trimesh tests/

# downgrade networkx from 2.x to 1.x to make sure our
# graph operations work on both versions of their API
- pip install -Iv networkx==1.11
- python -c "import networkx; print('::NX_VERSION::', networkx.__version__)"
- pytest tests/test_graph.py tests/test_scene.py

# make sure examples still work
- cd examples
- for f in *py*; do python ../tests/notebooks.py exec "$f"; done
- cd ..

after_success:
- coveralls