# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: continuumio/anaconda3
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install nose2
            pip install .
            python -c "import trimesh"
	    conda install -c conda-forge rtree shapely pyembree
	    pip install .[easy]
      - run:
          name: run tests
          command: nose2

      - store_artifacts:
          path: test-reports
          destination: test-reports
          